---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      run: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3.6.11-management
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-secret
              key: password
        ports:
        - containerPort: 25672
          name: clitool
          protocol: TCP
        - containerPort: 5672
          name: client-access-2
          protocol: TCP
        - containerPort: 5671
          name: client-access-1
          protocol: TCP
        - containerPort: 4369
          name: epmd
          protocol: TCP
        - containerPort: 15672
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  ports:
  - name: client-access-2
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: client-access-1
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: clitool
    port: 25672
    protocol: TCP
    targetPort: 25672
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  type: ClusterIP
  selector:
    run: rabbitmq
