---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit
data:
  rabbit.yaml: |-
    spring:
      rabbitmq:
        username: admin
        password: admin
        host: ${RABBITMQ_SERVICE_HOST}
        virtual-host: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  selector:
    matchLabels:
      run: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbit
    spec:
      containers:
      - name: rabbit
        image: ashraf1abdelrasool/rabbit:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    run: rabbit
spec:
  ports:
  - name: rabbit
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    run: rabbit
